---
title: "Code to read clustering tables"
subtitle: "In format of 'tfidf pings' sheet"
---

```{r load packages, message = F, warning = F}
library(tidyverse)
library(readr)
library(stringr)
```

```{r separating comma values}
tfidfpings1 = tfidf.pings.count...Sheet1 |>
  select(High.tf.idf.scoring.texts, Duplicate.Texts..from.above.categories.) |>
  mutate(High.tf.idf.scoring.texts = as.character(High.tf.idf.scoring.texts)) |>
  separate_rows(High.tf.idf.scoring.texts, sep = ",\\s+") |>
  separate_rows(Duplicate.Texts..from.above.categories., sep = ",\\s+") 

tfidfpings1
```

```{r table to list}
tfidfpings1_lists = tfidfpings1 |>
  as.list()

tfidfpings1_combined = append(tfidfpings1_lists[["High.tf.idf.scoring.texts"]], tfidfpings1_lists[["Duplicate.Texts..from.above.categories."]])
```

```{r count entries}
tfidfpings_table = table(unlist(lapply(tfidfpings1_combined, unique))) |>
  as.data.frame() |>
  subset(Var1 != "") |>
  group_by(Freq)

tfidfpings_table[order(-tfidfpings_table$Freq), ]
```

