---
format: html
---

```{r load packages, message = F, echo = F}
library(tidyverse)
library(plotly)
```

```{r get data, message = F, echo = F, output = F}
table = read.csv(r"(C:\Users\bqueu\Documents\R\ECBC Graphs\N-gram_Uni-gram List--final version - Bellarmine_Catholic_Bigram.csv)")
head(table)
```

```{r pivot table, echo = F}
table_pivot = table |>
  pivot_longer(
    cols = -X,
    names_to = "ngram",
    values_to = "frequency"
  )
table_pivot$X = sub("_", "-", table_pivot$X)
```

```{r graph, warning = F, echo = F}
p = table_pivot |>
  # filter(ngram %in% c("council_trent", "conventicle_trent", "decree_trent", "popish_council", "cardinal_trent", "bishop_trent", "trent_council", "lateran_trent", "trent_counsel", "trent_decree")) |>
  ggplot(aes(x = X, y = frequency, group = ngram, color = ngram)) +
  geom_line(size = .75) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  # scale_color_manual(values = c("#ff3333", "#eded2c", "#d2d2d2", "#add2ad", "#d2d2d2", "#7cabd0", "#d2d2d2", "#d2d2d2", "#d2d2d2", "#de4ab9", "#c596df", "#b5d0de", "#d2d2d2", "#d2d2d2")) +
  ylim(0, 20) +
  geom_vline(xintercept = 3, color = "red", size = 1, linetype = "longdash") +
  annotate("text", x = 4, y = 13, label = "King James I \n is coronated.", fontface = "italic", size = 3) +
  geom_vline(xintercept = 8, color = "red", size = 1, linetype = "longdash") +
  annotate("text", x = 9, y = 13, label = "King Charles I \n is coronated.", fontface = "italic", size = 3) +
  # annotate("rect", xmin = .3, xmax = 3, ymin = 0, ymax = 40, alpha = .25) +
  # annotate("rect", xmin = 8, xmax = 9, ymin = 0, ymax = 40, alpha = .25) +
  # annotate("rect", xmin = 3.5, xmax = 4.5, ymin = 0, ymax = 40, fill = "red", alpha = .25) +
  labs(
    title = "Discourse of Catholic N-grams Changed With Different Reigns",
    x = "Date", 
    y = "N-gram Frequency",
    color = "N-gram"
  ) 

ggplotly(p) |>
  layout(annotations = 
    list(x = 1.275, y = -.245, text = 
         "* King James was \n coronated in 1603, \n as was King Charles \n in 1625.
** Bigrams relate \n to English sentiments \n of Papal persecution.
*** In 1605, there \n were two Pope successions.", 
      showarrow = F, xref='paper', yref='paper', 
      xanchor='right', yanchor='auto', xshift=0, yshift=0,
      font=list(size=12, color="#4d4d4d", fontface = 'italic'))
 )
```
