---
format: html
---

```{r load packages, message = F, echo = F}
library(tidyverse)
library(plotly)
```

```{r get data, message = F, echo = F, output = F}
irish = read.csv(r"(C:\Users\bqueu\Documents\R\ECBC Graphs\N-gram_Uni-gram List--final version - Ireland_Bigram.csv)")
head(irish)
```

```{r pivot table, echo = F}
irish_pivot = irish |>
  pivot_longer(
    cols = -X,
    names_to = "ngram",
    values_to = "frequency"
  )
irish_pivot$X = sub("_", "-", irish_pivot$X)
```

```{r graph, warning = F, echo = F}
p = irish_pivot |>
  filter(ngram != "rebel_irish") |>
  ggplot(aes(x = X, y = frequency, group = ngram, color = ngram)) +
  geom_line(size = .75) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  scale_color_manual(values = c("#ffe699", "#ff76b3", "#eaadbd", "#990000", "#fa9026", "#3aa600")) +
  ylim(0, 40) +
  geom_vline(xintercept = "1600-1604", color = "red", size = 1, linetype = "longdash") +
  annotate("text", x = 5, y = 35, label = "Tyrone's Rebellion was \n mainly defeated in \n 1603.", fontface = "italic", size = 3.5) +
  annotate("rect", xmin = .3, xmax = 3, ymin = 0, ymax = 40, alpha = .25) +
  labs(
    title = "Negative N-grams Towards Irish \n Increase After Tyrone's Rebellion",
    x = "Date", 
    y = "N-gram Frequency",
    color = "N-gram", 
    caption = "NB: From 1610-1639, 'war_ireland' and \n 'rebel_ireland' have the same frequency."
  ) 

ggplotly(p)
```
