---
format: html
---

```{r load packages, message = F, echo = F}
library(tidyverse)
library(plotly)
```

```{r get data, message = F, echo = F, output = F}
spanish = read.csv(r"(C:\Users\bqueu\Documents\R\ECBC Graphs\N-gram_Uni-gram List--final version - Spanish_Bigram.csv)")
head(spanish)
```

```{r pivot table, echo = F}
spanish_pivot = spanish |>
  pivot_longer(
    cols = -X,
    names_to = "ngram",
    values_to = "frequency"
  )
spanish_pivot$X = sub("_", "-", spanish_pivot$X)
```

```{r graph, warning = F, echo = F}
p = spanish_pivot |>
  filter(ngram != "spaniard_slay", ngram != "spaniard_negro", ngram != "spain_moor", ngram != "cruelty_spaniard", ngram != "spanish_cruelty") |>
  ggplot(aes(x = X, y = frequency, group = ngram, color = ngram)) +
  geom_line(size = .75) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  scale_color_manual(values = c("#c9c6d2", "#eaadbd", "#ffedb3", "#990000", "#33ff77")) +
  ylim(0, 25) +
  # geom_vline(xintercept = "1600-1604", color = "red", size = 1, linetype = "longdash") +
  # annotate("text", x = 5, y = 35, label = "Tyrone's Rebellion was \n mainly defeated in \n 1603.", fontface = "italic", size = 2.5) +
  # annotate("rect", xmin = .3, xmax = 3, ymin = 0, ymax = 40, alpha = .25) +
  labs(
    title = "'War_Spainiard' Has Similar Contour \n to Other New-World Spanish N-grams.",
    x = "Date", 
    y = "N-gram Frequency",
    color = "N-gram"
  ) 

ggplotly(p)
```
